[package]
name = "icon_baker"
version = "1.2.0"
authors = ["Gark Garcia <thiago.brevidelli.garcia@protonmail.com>"]
edition = "2018"
description = "A simple solution for generating .ico and .icns icons."
license-file = "LICENSE"
repository = "https://github.com/GarkGarcia/icon_baker"
homepage = "https://github.com/GarkGarcia/icon_baker"
readme = "README.md"
keywords = ["icon", "ico", "icns"]

[dependencies]
zip = "0.5.2"
png_encode_mini = "0.1.2"
nsvg = "0.5.0"
ico = "0.1.0"
icns = "0.3.0"